/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TovButton: typeof import('tov-ui')['TovButton']
    TovInput: typeof import('tov-ui')['TovInput']
    TovTable: typeof import('tov-ui')['TovTable']
    TovTableColumn: typeof import('tov-ui')['TovTableColumn']
    TovTooltip: typeof import('tov-ui')['TovTooltip']
    TovVirtuallist: typeof import('tov-ui')['TovVirtuallist']
  }
}
