/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TovButton: typeof import('tov-ui')['TovButton']
    TovTooltip: typeof import('tov-ui')['TovTooltip']
  }
}
